# Generated by Django 4.2.2 on 2023-07-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
