# Generated by Django 4.2.2 on 2023-07-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
